import { useState, useRef } from "react";

const JURISDICTIONS = {
  "Abilene": { code: "IPC 2021", population: "117K", region: "West Texas", amendments: ["All backflow testing must conform to Abilene Cross Connection Ordinance", "Commercial kitchens: floor sinks accepted in lieu of floor drains at Code Official discretion", "Water heaters above ground or floor: must meet Section 502.6 local requirements", "Attic appliance access: specific local rules on means of accessibility apply", "TPR valve discharge must terminate at approved locations per local amendment"], inspector: "Abilene Building Inspections", phone: "(325) 676-6273", permitRequired: true, permitUrl: "abilenetx.gov/431/Adopted-Codes", thirdParty: ["Texas Third Party Inspections LLC", "Bureau Veritas", "Fox Energy Specialists"] },
  "Allen": { code: "IPC 2021", population: "107K", region: "North Texas (DFW)", amendments: ["NCTCOG regional amendments apply", "All permits through Citizen Self-Service (CSS) portal before work begins", "Inspection time window: call (214) 509-4130 between 8-9 AM on day of inspection", "Stopping leaks in existing pipes does not require permit — replacing defective pipe does", "Backflow prevention required — irrigation backflow tester must be licensed and registered", "Call 811 before any excavation for underground plumbing"], inspector: "Allen Building & Permitting", phone: "(214) 509-4130", permitRequired: true, permitUrl: "cityofallen.org/building-permitting", thirdParty: ["Crossroads Inspections", "Master Code", "Bureau Veritas", "Roadrunner Inspections"] },
  "Amarillo": { code: "IPC 2021", population: "200K", region: "Texas Panhandle", amendments: ["Roof vents must terminate with a listed and labeled cap per manufacturer specs", "Clothes dryer exhaust must terminate outside with backdraft damper — no screens", "Sanitary facilities required for all construction workers per IPC Section 311", "Pressure test required — document start and end PSI with inspector notification", "Review Ordinance 7101 for all local amendments"], inspector: "Amarillo Building Safety", phone: "(806) 378-3033", permitRequired: true, permitUrl: "amarillo.gov/building-safety", thirdParty: ["Texas Third Party Inspections LLC", "Bureau Veritas"] },
  "Arlington": { code: "IPC 2021", population: "394K", region: "North Texas (DFW)", amendments: ["All permits handled through Accela online portal — required before work begins", "Plumbing permit required for any installation, replacement, or alteration", "Inspection requests must be submitted before 7AM on the day needed", "Energy compliance forms required for applicable plumbing work", "NCTCOG regional amendments apply"], inspector: "Arlington Development Services", phone: "(817) 459-6502", permitRequired: true, permitUrl: "arlingtontx.gov/permits", thirdParty: ["Crossroads Inspections", "Master Code", "Code Solutions Inc.", "Bureau Veritas", "L3 Inspections"] },
  "Austin": { code: "UPC 2021 ⚠", population: "978K", region: "Central Texas", amendments: ["⚠ IMPORTANT: Austin uses the Uniform Plumbing Code (UPC) — NOT the IPC", "Reclaimed water rough-in required on all new construction", "Low-flow fixtures mandatory: 1.28 GPF max on toilets", "Green building code overlay applies in designated zones", "Rain water harvesting systems must have backflow protection"], inspector: "Austin Development Services", phone: "(512) 978-4000", permitRequired: true, permitUrl: "austintexas.gov/permits", thirdParty: ["Veritas Inspections", "Crossroads Inspections", "Fox Energy Specialists", "Burgess Construction Consultants"], warning: "Austin uses the UPC, not the IPC. Surrounding cities (Round Rock, Cedar Park, Kyle, Georgetown) use the IPC. Always confirm before pulling a permit near the Austin city limits." },
  "Beaumont": { code: "IPC 2021", population: "113K", region: "Southeast Texas", amendments: ["Journeyman plumber must be present and in direct supervision on all permitted work", "One journeyman may supervise no more than 3 unclassified workers on site", "Ordinance 24-011 (adopted 3/19/2024) contains latest local amendments", "Where IBC or IRC conflicts with IPC — IBC/IRC shall prevail"], inspector: "Beaumont Building Codes", phone: "(409) 880-3763", permitRequired: true, permitUrl: "beaumonttexas.gov", thirdParty: ["Bureau Veritas", "ECS Limited", "Texas Third Party Inspections LLC"] },
  "Bedford": { code: "IPC 2021", population: "49K", region: "North Texas (HEB Area)", amendments: ["NCTCOG regional amendments apply", "HEB area — Hurst, Euless, and Bedford share similar code environment", "Thermal expansion tank required on all closed water systems", "CSST bonding required per NFPA 54", "Water heater elevation required in garage — 18\" minimum off floor", "Backflow prevention required on all irrigation connections"], inspector: "Bedford Building Inspections", phone: "(817) 952-2200", permitRequired: true, permitUrl: "bedfordtx.gov/permits", thirdParty: ["Crossroads Inspections", "Master Code", "Bureau Veritas", "Code Solutions Inc."] },
  "Brownsville": { code: "IPC 2021", population: "186K", region: "Rio Grande Valley", amendments: ["Border city: verify utility connections with Brownsville Public Utilities Board (PUB)", "PUB approval required before water service connections", "Backflow prevention required on all irrigation and commercial connections", "High humidity and heat — corrosion protection on metal piping recommended", "Gas pressure test: 10 PSI for 15 minutes minimum"], inspector: "Brownsville Building Inspections", phone: "(956) 548-6060", permitRequired: true, permitUrl: "brownsvilletx.gov/permits", thirdParty: ["Bureau Veritas", "ECS Limited", "Texas Third Party Inspections LLC"] },
  "Burleson": { code: "IPC 2021", population: "50K", region: "North Texas (Fort Worth suburb)", amendments: ["NCTCOG regional amendments apply", "Johnson/Tarrant county line — verify which county governs your specific address", "Thermal expansion tank required on all closed water systems", "CSST bonding required per NFPA 54", "Fire code review: required to be submitted to an accepted third-party before Fire Marshal submittal", "All permits through city portal before work begins"], inspector: "Burleson Building Permits & Inspections", phone: "(817) 426-9600", permitRequired: true, permitUrl: "burlesontx.com/building", thirdParty: ["Crossroads Inspections", "Code Solutions Inc.", "Bureau Veritas", "Master Code"] },
  "Carrollton": { code: "IPC 2021", population: "135K", region: "North Texas (DFW)", amendments: ["NCTCOG regional amendments apply", "Permits required for repairs or replacement of any MEP system — not just new work", "General maintenance (painting, cabinets, trim) does not require a permit", "Permits required even for partial replacements of defective plumbing systems", "Thermal expansion tank required on all closed water systems", "CSST bonding required per NFPA 54"], inspector: "Carrollton Building Inspection", phone: "(972) 466-3016", permitRequired: true, permitUrl: "cityofcarrollton.com/building-inspection", thirdParty: ["Crossroads Inspections", "Master Code", "Bureau Veritas", "Roadrunner Inspections"] },
  "Cedar Hill": { code: "IPC 2021", population: "48K", region: "North Texas (DFW)", amendments: ["NCTCOG regional amendments apply", "Thermal expansion tank required on all closed water systems", "CSST bonding required per NFPA 54", "Water heater elevated 18\" in garage — strictly enforced", "Backflow prevention required on all irrigation connections", "All permits required before work begins"], inspector: "Cedar Hill Building Inspections", phone: "(972) 291-5100", permitRequired: true, permitUrl: "cedarhilltx.com/permits", thirdParty: ["Crossroads Inspections", "Master Code", "Bureau Veritas"] },
  "Cedar Park": { code: "IPC 2021", population: "82K", region: "Central Texas", amendments: ["IPC adopted — Cedar Park switched from UPC", "Plumbing permit required for all work — same-day permits available for simple replacements", "CPPID (Cedar Park utility) pre-approval required for new water service connections", "Thermal expansion tank required on all water heater installs", "Backflow prevention required on all irrigation connections"], inspector: "Cedar Park Development Services", phone: "(512) 401-5000", permitRequired: true, permitUrl: "cedarparktexas.gov/permits", thirdParty: ["Fox Energy Specialists", "Crossroads Inspections", "Burgess Construction Consultants", "Bureau Veritas"] },
  "Cleburne": { code: "IPC 2021", population: "32K", region: "North Texas (Johnson County)", amendments: ["Johnson County seat — verify MUD rules if working in outer areas", "Permits required for all plumbing installations, alterations, and repairs", "Gas pressure test: 10 PSI minimum — inspector notification required", "Thermal expansion tank required on all closed water systems", "Backflow prevention required on all irrigation connections"], inspector: "Cleburne Building Inspections", phone: "(817) 645-0958", permitRequired: true, permitUrl: "cleburne.net/permits", thirdParty: ["Code Solutions Inc.", "Bureau Veritas", "Texas Third Party Inspections LLC"] },
  "Conroe": { code: "IPC 2021", population: "106K", region: "Greater Houston", amendments: ["All permits and inspections through OpenGov portal (effective December 8, 2025)", "Permit fees updated November 2025 — verify current fee schedule on portal", "Morning inspections: schedule before 7AM same day", "Afternoon inspections: schedule between 7AM and noon same day", "Montgomery County MUD rules may apply in outer areas — verify jurisdiction", "CSISD and Woodlands areas: confirm jurisdiction before pulling permit"], inspector: "Conroe Building Inspections", phone: "(936) 522-3610", permitRequired: true, permitUrl: "cityofconroe.org/building-inspections", thirdParty: ["Fox Energy Specialists", "Bureau Veritas", "Burgess Construction Consultants", "Crossroads Inspections"] },
  "Corpus Christi": { code: "IPC 2021", population: "317K", region: "Coastal Bend", amendments: ["2021 IPC adopted with local amendments effective August 1, 2023", "Storm water, fill materials, and excavation requirements apply at construction sites", "Amendments published in MuniCode — verify before pulling permit", "Swimming Pool and Spa Code 2021 adopted separately", "NEC 2020 applies to all electrical work on plumbing-related equipment"], inspector: "CC Development Services", phone: "(361) 826-3240", permitRequired: true, permitUrl: "corpuschristitx.gov/development-services", thirdParty: ["Bureau Veritas", "ECS Limited", "Veritas Inspections"] },
  "Dallas": { code: "IPC 2021", population: "1.3M", region: "North Texas", amendments: ["Thermal expansion tanks mandatory on all closed water systems", "PEX-A only permitted for in-slab installations (PEX-B not allowed)", "Isolation valve required at each individual fixture", "Water heater must be elevated 18\" off floor in garage", "CSST bonding required per NFPA 54 — inspector will verify"], inspector: "Dallas Development Services", phone: "(214) 948-4480", permitRequired: true, permitUrl: "dallascityhall.com/permits", thirdParty: ["Crossroads Inspections", "Roadrunner Inspections", "Master Code", "Bureau Veritas", "Code Solutions Inc."] },
  "Denton": { code: "IPC 2021", population: "148K", region: "North Texas", amendments: ["NCTCOG regional amendments apply", "Thermal expansion tank required on all closed water systems", "CSST must be bonded per NFPA 54 requirements", "Underground plastic sewer piping requires tracer wire", "Backfill requirements: 4\" granular base, 6\" compacted layers"], inspector: "Denton Development Services", phone: "(940) 349-8360", permitRequired: true, permitUrl: "cityofdenton.com/permits", thirdParty: ["Crossroads Inspections", "Bureau Veritas", "Master Code", "Fox Energy Specialists"] },
  "El Paso": { code: "IPC 2021", population: "678K", region: "Far West Texas", amendments: ["Desert climate: water conservation fixtures mandatory on all new construction", "Seismic zone requirements apply — water heater strapping required", "El Paso Water approval required before water service connections", "Reclaimed water infrastructure available — consult EPWater for new construction", "Gas pressure test: 10 PSI minimum, witnessed by inspector"], inspector: "El Paso Development Services", phone: "(915) 212-0104", permitRequired: true, permitUrl: "elpasotexas.gov/development-services", thirdParty: ["Bureau Veritas", "ECS Limited", "Texas Third Party Inspections LLC"] },
  "Euless": { code: "IPC 2021", population: "56K", region: "North Texas (HEB Area)", amendments: ["NCTCOG regional amendments apply", "HEB area — Hurst, Euless, and Bedford share similar code environment", "Thermal expansion tank required on all closed water systems", "CSST bonding required per NFPA 54", "Backflow prevention required on all irrigation systems", "All permits required before work begins"], inspector: "Euless Building Inspections", phone: "(817) 685-1400", permitRequired: true, permitUrl: "eulesscityhall.com/permits", thirdParty: ["Crossroads Inspections", "Master Code", "Bureau Veritas"] },
  "Flower Mound": { code: "IPC 2024 ⚠", population: "82K", region: "North Texas (DFW)", amendments: ["⚠ Flower Mound adopted IPC 2024 effective October 1, 2025", "Emergency permits available same-day — call (972) 874-6355 before 3:30PM, inspector arrives within 1 hour", "Emergency plumbing permits apply for buildings without gas, water, or sewer only", "For emergency work after hours: perform work, then obtain permit next business day", "Water heater pan required wherever leakage would cause property damage", "Irrigation and pool permits required — pool must hold 749+ gallons to require permit", "Water heater permit required even for emergency — get it next business day if after hours"], inspector: "Flower Mound Building Inspections", phone: "(972) 874-6355", permitRequired: true, permitUrl: "flowermound.gov/building", thirdParty: ["Crossroads Inspections", "Master Code", "Bureau Veritas", "Roadrunner Inspections"], warning: "Flower Mound is on IPC 2024 effective October 1, 2025. Key changes: 2.0 GPM max showerheads, tracer wire on buried plastic sewer. Review 2024 IPC changes before pulling permits here." },
  "Forney": { code: "IPC 2021", population: "30K", region: "North Texas (Kaufman County)", amendments: ["NCTCOG regional amendments apply", "Fast-growing suburb — verify MUD jurisdiction before pulling permit on new subdivisions", "Thermal expansion tank required on all closed water systems", "CSST bonding required per NFPA 54", "Backflow prevention required on all irrigation connections", "All permits required before work begins"], inspector: "Forney Building Inspections", phone: "(972) 564-7300", permitRequired: true, permitUrl: "forneytx.gov/permits", thirdParty: ["Crossroads Inspections", "Master Code", "Bureau Veritas"] },
  "Fort Worth": { code: "IPC 2021", population: "935K", region: "North Texas", amendments: ["Copper or CPVC only for water service pipe inside slab", "Water heater pan and drain required in all locations", "Shower valve must be pressure-balance or thermostatic type", "Cleanout required within 5 ft of building foundation", "All gas work requires licensed master plumber signature"], inspector: "Fort Worth Development", phone: "(817) 392-2222", permitRequired: true, permitUrl: "fortworthtexas.gov/permits", thirdParty: ["Code Solutions Inc.", "Master Code", "Bureau Veritas", "Crossroads Inspections", "ECS Limited"] },
  "Frisco": { code: "IPC 2024 ⚠", population: "230K", region: "North Texas (DFW)", amendments: ["⚠ Frisco adopted IPC 2024 effective March 1, 2026", "NCTCOG regional amendments apply alongside 2024 IPC local amendments", "New 2024 IPC: showerhead flow now limited to 2.0 GPM", "New 2024 IPC: tracer wire required on buried plastic sewer piping", "Thermal expansion tank required on all water heater installs", "Underground gas lines require PE pipe with tracer wire"], inspector: "Frisco Development Services", phone: "(972) 292-5330", permitRequired: true, permitUrl: "friscotexas.gov/permits", thirdParty: ["Crossroads Inspections", "Bureau Veritas", "Master Code", "Roadrunner Inspections"], warning: "Frisco moved to IPC 2024 on March 1, 2026. Key changes: 2.0 GPM max showerheads and tracer wire on buried plastic sewer." },
  "Garland": { code: "IPC 2021", population: "238K", region: "North Texas (DFW)", amendments: ["NCTCOG regional amendments apply", "Thermal expansion tanks required on all closed systems", "CSST bonding required — inspector will verify clamp placement", "Water heater elevated 18\" in garage — strictly enforced", "All permits must be obtained before work commences"], inspector: "Garland Building Inspections", phone: "(972) 205-2350", permitRequired: true, permitUrl: "garlandtx.gov/building", thirdParty: ["Crossroads Inspections", "Master Code", "Bureau Veritas"] },
  "Georgetown": { code: "IPC 2021", population: "90K", region: "Central Texas", amendments: ["IPC adopted — Georgetown switched from UPC", "Williamson County MUD rules may apply in outer development areas", "Thermal expansion tank required on all water heater installs", "Backflow prevention required on all irrigation connections", "Plumbing permit required before any work — online submission available"], inspector: "Georgetown Development Services", phone: "(512) 930-3456", permitRequired: true, permitUrl: "georgetown.org/permits", thirdParty: ["Fox Energy Specialists", "Bureau Veritas", "Crossroads Inspections", "Burgess Construction Consultants"] },
  "Grand Prairie": { code: "IPC 2021", population: "196K", region: "North Texas (DFW)", amendments: ["NCTCOG regional amendments apply", "Straddles Dallas and Tarrant counties — confirm which jurisdiction governs your job address", "Thermal expansion tank required on closed water systems", "Shower valves must be pressure-balance or thermostatic", "Gas test: 10 PSI for 30 minutes minimum"], inspector: "Grand Prairie Building Inspections", phone: "(972) 237-8255", permitRequired: true, permitUrl: "gptx.org/permits", thirdParty: ["Crossroads Inspections", "Code Solutions Inc.", "Bureau Veritas", "Master Code"], warning: "Grand Prairie spans Dallas and Tarrant counties. Always confirm the exact jurisdiction for your job address before pulling a permit." },
  "Grapevine": { code: "IPC 2021", population: "55K", region: "North Texas (DFW)", amendments: ["IPC 2021 adopted effective January 1, 2024", "NCTCOG regional amendments apply", "Thermal expansion tank required on all closed water systems", "CSST bonding required per NFPA 54", "Water heater elevated 18\" in garage", "Backflow prevention required on all irrigation connections"], inspector: "Grapevine Building Inspections", phone: "(817) 410-3165", permitRequired: true, permitUrl: "grapevinetexas.gov/permits", thirdParty: ["Crossroads Inspections", "Master Code", "Bureau Veritas", "Code Solutions Inc."] },
  "Houston": { code: "UPC 2021 ⚠", population: "2.3M", region: "Gulf Coast", amendments: ["⚠ IMPORTANT: Houston uses the Uniform Plumbing Code (UPC) — NOT the IPC", "Effective January 1, 2024 per Ordinance No. 2023-907", "Backflow preventer required on all irrigation systems", "Thermal expansion tank required on all water heater installs", "All new construction requires low-flow fixtures (1.5 GPM max lavatory)", "Gas pressure test: 10 PSI minimum hold for 30 minutes"], inspector: "Houston Permitting Center", phone: "(832) 394-8800", permitRequired: true, permitUrl: "houstonpermittingcenter.org", thirdParty: ["Crossroads Inspections", "Veritas Inspections", "Bureau Veritas", "Burgess Construction Consultants", "Fox Energy Specialists"], warning: "Houston uses the UPC, not the IPC. If you work in both Houston and surrounding cities, the codes differ — especially for venting, pipe sizing, and gas systems." },
  "Hurst": { code: "IPC 2021", population: "39K", region: "North Texas (HEB Area)", amendments: ["NCTCOG regional amendments apply", "HEB area — Hurst, Euless, and Bedford share similar code environment", "Thermal expansion tank required on all closed water systems", "CSST bonding required per NFPA 54", "Water heater pan required in locations where leakage could cause damage", "Backflow prevention required on all irrigation connections"], inspector: "Hurst Building Inspections", phone: "(817) 788-7025", permitRequired: true, permitUrl: "hursttx.gov/permits", thirdParty: ["Crossroads Inspections", "Master Code", "Bureau Veritas"] },
  "Irving": { code: "IPC 2021", population: "240K", region: "North Texas (DFW)", amendments: ["NCTCOG regional amendments apply", "Permits required through Irving's online portal before any work begins", "Thermal expansion tank required on all closed water systems", "CSST bonding required per NFPA 54", "Water heater elevation required in garage — 18\" minimum off floor", "Tracer wire required on all underground plastic piping"], inspector: "Irving Building Inspections", phone: "(972) 721-2371", permitRequired: true, permitUrl: "cityofirving.org/permits", thirdParty: ["Crossroads Inspections", "Master Code", "Bureau Veritas", "L3 Inspections"] },
  "Katy": { code: "IPC 2021", population: "22K", region: "Greater Houston", amendments: ["Harris County MUD rules apply outside city limits — verify jurisdiction first", "Expansion tank required on all water heater replacements", "Permit required for any water heater replacement regardless of size", "Gas test: 10 PSI for 30 min — inspector must witness", "Water service: copper only within 5 ft of meter"], inspector: "Katy Building Department", phone: "(281) 391-4800", permitRequired: true, permitUrl: "cityofkaty.com", thirdParty: ["Crossroads Inspections", "Roadrunner Inspections", "Bureau Veritas", "Fox Energy Specialists"] },
  "Keller": { code: "IPC 2021", population: "48K", region: "North Texas (DFW)", amendments: ["IPC 2021 International I-Codes adopted", "NCTCOG regional amendments apply", "⚠ Customer service inspection required before scheduling final inspection on any project affecting plumbing water supply or irrigation", "Thermal expansion tank required on all closed water systems", "CSST bonding required per NFPA 54", "Backflow prevention required on all irrigation connections"], inspector: "Keller Building Services", phone: "(817) 743-4000", permitRequired: true, permitUrl: "cityofkeller.com/building", thirdParty: ["Crossroads Inspections", "Master Code", "Bureau Veritas", "Code Solutions Inc."], warning: "Keller requires a customer service inspection before you can schedule a final inspection on any project that affected water supply or irrigation. Don't skip this step or your final will be blocked." },
  "Killeen": { code: "IPC 2024 ⚠", population: "155K", region: "Central Texas", amendments: ["⚠ Killeen adopted IPC 2024 as amended — among the most current adoptions in Texas", "Permits through MGO Connect portal — paperless system", "New 2024 IPC: showerhead flow limited to 2.0 GPM", "New 2024 IPC: tracer wire required on buried plastic sewer piping", "2024 IFGC applies to all gas work — verify amendments in Chapter 8, Killeen Code of Ordinances", "Plumbing rough-in underground: 5 PSI air test allowed during wet weather only"], inspector: "Killeen Building Inspections", phone: "(254) 501-7640", permitRequired: true, permitUrl: "killeentexas.gov/building-inspections", thirdParty: ["Bureau Veritas", "Texas Third Party Inspections LLC", "ECS Limited"], warning: "Killeen is on IPC 2024. Key changes from 2021: 2.0 GPM max showerheads, tracer wire on buried plastic sewer. Verify all 2024 IPC changes before pulling permits here." },
  "Laredo": { code: "IPC 2021", population: "255K", region: "South Texas (Border)", amendments: ["IBWC and USFWS coordination may be required near the Rio Grande", "Water service connections require Laredo Water (LWWD-DC) pre-approval", "Backflow prevention required on all commercial and irrigation connections", "High mineral content in local water — additional water heater protection recommended", "Gas pressure test: 10 PSI hold for 15 minutes minimum"], inspector: "Laredo Building Development Services", phone: "(956) 794-1620", permitRequired: true, permitUrl: "ci.laredo.tx.us/building", thirdParty: ["Bureau Veritas", "ECS Limited", "Texas Third Party Inspections LLC"] },
  "League City": { code: "IPC 2021", population: "117K", region: "Greater Houston", amendments: ["Galveston County jurisdiction — verify MUD or ETJ rules before pulling permit", "IPC 2021 adopted — verify current edition before permit", "Thermal expansion tank required on all water heater installs", "Backflow prevention required on all irrigation connections", "Gas pressure test: 10 PSI minimum for 30 minutes"], inspector: "League City Inspections", phone: "(281) 554-1060", permitRequired: true, permitUrl: "leaguecitytx.gov/permits", thirdParty: ["Fox Energy Specialists", "Bureau Veritas", "Crossroads Inspections", "Roadrunner Inspections"] },
  "Lewisville": { code: "IPC 2021", population: "115K", region: "North Texas (DFW)", amendments: ["NCTCOG regional amendments apply", "Thermal expansion tank required on all closed systems", "Water softener loop rough-in required on new construction", "CSST bonding required and verified at rough-in inspection", "Underground plastic sewer requires tracer wire"], inspector: "Lewisville Development Services", phone: "(972) 219-3500", permitRequired: true, permitUrl: "cityoflewisville.com/permits", thirdParty: ["Crossroads Inspections", "Bureau Veritas", "Master Code", "Fox Energy Specialists"] },
  "Longview": { code: "IPC 2021", population: "82K", region: "East Texas", amendments: ["All inspection requests through automated line: (903) 239-5598", "Inspections cover plumbing, gas, medical gas, and vacuum systems", "Plan review required for all commercial and residential construction", "Permits required before construction, additions, alterations, or repairs", "Gas pressure test required — document results for inspector"], inspector: "Longview Building Inspection", phone: "(903) 239-5598", permitRequired: true, permitUrl: "longviewtexas.gov/building-inspection", thirdParty: ["Bureau Veritas", "ECS Limited", "Texas Third Party Inspections LLC"] },
  "Lubbock": { code: "IPC 2021", population: "258K", region: "West Texas", amendments: ["Adopted IPC 2021 via Ordinance 2024-O0026 (adopted 3/26/2024)", "Backflow prevention: all connections must comply with 30 TAC 290.44(h) and 30 TAC 344.73", "Water service connections require protection per state law — no exceptions", "Comprehensive backflow assembly tester program — tester must be certified", "Slab inspection required before concrete pour — schedule early"], inspector: "Lubbock Building Safety", phone: "(806) 775-2087", permitRequired: true, permitUrl: "ci.lubbock.tx.us/departments/building-safety", thirdParty: ["Bureau Veritas", "Texas Third Party Inspections LLC", "ECS Limited"] },
  "Mansfield": { code: "IPC 2018 ⚠", population: "77K", region: "North Texas (DFW)", amendments: ["⚠ Mansfield is on IPC 2018 — older than most surrounding DFW cities", "Inspection requests submitted by 4PM are inspected the next business day", "Requests submitted after 4PM Friday through 8AM Monday scheduled for Tuesday", "Granular bedding required: 4\" base, 6\" compacted side layers on underground piping", "Commercial kitchens: Code official may accept floor sinks in lieu of floor drains", "All backflow testers must register with Vepo LLC before working in Mansfield", "Single trade permits (plumbing, electrical, mechanical) submitted via MyGov system"], inspector: "Mansfield Building Safety", phone: "(817) 276-4200", permitRequired: true, permitUrl: "mansfieldtexas.gov/building", thirdParty: ["Crossroads Inspections", "Code Solutions Inc.", "Bureau Veritas", "Master Code"], warning: "Mansfield is on IPC 2018 — older than most surrounding DFW cities. Verify code edition requirements carefully before pulling permits here as requirements differ from IPC 2021 cities." },
  "McAllen": { code: "IPC 2024 ⚠", population: "143K", region: "Rio Grande Valley", amendments: ["⚠ McAllen adopted 2024 ICC codes effective January 1, 2026", "Saturday inspections now available 8:30AM–4:30PM — request Friday 12–4PM", "New 2024 IPC: showerhead flow limited to 2.0 GPM", "New 2024 IPC: tracer wire required on buried plastic sewer piping", "Plumbing rough-in underground: verify setbacks, property lines strung up for inspection", "5 PSI air test allowed for plumbing rough-in during wet weather only"], inspector: "McAllen Building Permits & Inspections", phone: "(956) 681-1300", permitRequired: true, permitUrl: "mcallen.net/permits", thirdParty: ["Bureau Veritas", "ECS Limited", "Texas Third Party Inspections LLC"], warning: "McAllen moved to IPC 2024 effective January 1, 2026. Saturday inspections now available. Request inspection line: (956) 681-1328." },
  "McKinney": { code: "IPC 2021", population: "222K", region: "North Texas", amendments: ["All new residential requires recirculation on hot water systems over 50 ft", "Water softener loop required roughed in on all new construction", "Dual check backflow required on all irrigation systems", "Fire sprinkler systems require separate permit and inspection", "Underground gas: PE pipe only with tracer wire"], inspector: "McKinney Development Services", phone: "(972) 547-7400", permitRequired: true, permitUrl: "mckinneytexas.org/permits", thirdParty: ["Crossroads Inspections", "Master Code", "Bureau Veritas"] },
  "Mesquite": { code: "IPC 2021", population: "145K", region: "North Texas (DFW)", amendments: ["NCTCOG regional amendments apply", "Thermal expansion tank required on all water heater installs with closed systems", "CSST bonding required — verified at rough-in", "Water heater in garage must be elevated 18\" minimum", "All permits must be pulled before work begins — no after-the-fact permits"], inspector: "Mesquite Building Inspections", phone: "(972) 216-6200", permitRequired: true, permitUrl: "cityofmesquite.com/permits", thirdParty: ["Crossroads Inspections", "Master Code", "Bureau Veritas"] },
  "Midland": { code: "IPC 2021", population: "132K", region: "West Texas (Permian Basin)", amendments: ["Permian Basin: high soil expansion — underground piping bedding requirements strictly enforced", "Water heater strapping required — seismic and soil movement precautions", "Backflow prevention required on all irrigation and industrial connections", "Gas pressure test: 10 PSI for 30 minutes — common on oilfield-adjacent properties", "Permits required for all plumbing work including water heater replacements"], inspector: "Midland Building Inspections", phone: "(432) 685-7444", permitRequired: true, permitUrl: "midlandtexas.gov/permits", thirdParty: ["Bureau Veritas", "ECS Limited", "Texas Third Party Inspections LLC"] },
  "Mansfield_skip": null,
  "New Braunfels": { code: "IPC 2021", population: "107K", region: "Central Texas", amendments: ["IPC adopted — New Braunfels switched from UPC", "All plans submitted through ProjectDox electronic plan review software", "Plumbing permits available online as standalone permit", "Permit required for all new, enlarged, altered, repaired, or replaced plumbing systems", "Thermal expansion tank required on all water heater installs", "Comal County and Guadalupe County MUD rules may apply in outer areas"], inspector: "New Braunfels Development Services", phone: "(830) 221-4020", permitRequired: true, permitUrl: "newbraunfels.gov/buildingpermits", thirdParty: ["Bureau Veritas", "Fox Energy Specialists", "Texas Third Party Inspections LLC", "Burgess Construction Consultants"] },
  "North Richland Hills": { code: "IPC 2021", population: "74K", region: "North Texas (DFW)", amendments: ["NCTCOG regional amendments apply", "Thermal expansion tank required on all closed water systems", "CSST bonding required per NFPA 54", "Water heater elevated 18\" in garage", "Backflow prevention required on all irrigation connections", "All permits required before work begins"], inspector: "NRH Building Inspections", phone: "(817) 427-6300", permitRequired: true, permitUrl: "nrhtx.com/permits", thirdParty: ["Crossroads Inspections", "Master Code", "Bureau Veritas", "Code Solutions Inc."] },
  "Odessa": { code: "IPC 2021", population: "114K", region: "West Texas (Permian Basin)", amendments: ["Permian Basin: expansive soil — granular bedding required for all underground piping", "Water heater strapping required at all locations", "Industrial and oilfield connections: RPZ backflow required", "Gas systems: additional documentation may be required on commercial oilfield-adjacent work", "Permits required before work begins — no exceptions"], inspector: "Odessa Building Inspections", phone: "(432) 335-3265", permitRequired: true, permitUrl: "odessatx.gov/permits", thirdParty: ["Bureau Veritas", "ECS Limited", "Texas Third Party Inspections LLC"] },
  "Pasadena": { code: "IPC 2021", population: "151K", region: "Greater Houston", amendments: ["Located in Harris County — verify MUD jurisdiction before pulling permit", "UPC used by neighboring Houston — confirm which code governs your job site", "Backflow prevention required on all irrigation connections", "Thermal expansion tank required on all water heater installs", "Gas test: 10 PSI minimum for 30 minutes"], inspector: "Pasadena Building Inspections", phone: "(713) 475-5560", permitRequired: true, permitUrl: "ci.pasadena.tx.us/permits", thirdParty: ["Fox Energy Specialists", "Bureau Veritas", "Crossroads Inspections", "Roadrunner Inspections"], warning: "Pasadena borders Houston which uses the UPC. Confirm which code governs your specific job address before pulling a permit." },
  "Pearland": { code: "IPC 2021", population: "125K", region: "Greater Houston", amendments: ["Adopted IPC 2021 — verify current edition on city website before permit", "Brazoria County MUD rules may apply in portions of Pearland — verify jurisdiction", "Thermal expansion tank required on all water heater installs", "Backflow prevention required on all irrigation systems", "Water service connections require city pre-approval"], inspector: "Pearland Community Development", phone: "(281) 652-1600", permitRequired: true, permitUrl: "pearlandtx.gov/departments/community-development", thirdParty: ["Fox Energy Specialists", "Bureau Veritas", "Burgess Construction Consultants", "Crossroads Inspections"] },
  "Pflugerville": { code: "IPC 2021", population: "74K", region: "Central Texas", amendments: ["Follows IPC — confirm overlay before pulling permit", "Tap fees paid to Pflugerville MUD before permit issuance", "Backflow test report required within 30 days of installation", "MUD inspection required separately from city inspection", "Call 811 required and documentation submitted with permit"], inspector: "Pflugerville Building Inspections", phone: "(512) 990-6100", permitRequired: true, permitUrl: "cityofpflugerville.com/permits", thirdParty: ["Fox Energy Specialists", "Burgess Construction Consultants", "Crossroads Inspections"] },
  "Plano": { code: "IPC 2024 ⚠", population: "285K", region: "North Texas (DFW)", amendments: ["⚠ Plano adopted IPC 2024 effective August 1, 2025", "NCTCOG regional amendments apply alongside 2024 IPC local amendments", "New 2024 IPC: showerhead flow limited to 2.0 GPM", "New 2024 IPC: tracer wire required on buried plastic sewer piping", "Thermal expansion tank required on all closed water systems", "Water softener loop required on all new residential construction", "Permits through Accela portal — online submission required"], inspector: "Plano Building Inspections", phone: "(972) 941-7151", permitRequired: true, permitUrl: "plano.gov/permits", thirdParty: ["Crossroads Inspections", "Master Code", "Bureau Veritas", "Roadrunner Inspections"], warning: "Plano moved to IPC 2024 on August 1, 2025. Key changes: 2.0 GPM max showerheads, tracer wire on buried plastic sewer." },
  "Prosper": { code: "IPC 2021", population: "42K", region: "North Texas (DFW)", amendments: ["CSS portal for permits — search registered contractors by type", "Permits expire 180 days from issuance or last approved inspection", "General contractor pulls main permit and lists all subcontractors", "Subcontractors must be registered to work in Prosper", "Subcontractor separate permit required if work done after main permit is finaled", "Fee schedule amendment effective October 1, 2025 — verify current fees"], inspector: "Prosper Building Inspections", phone: "(972) 346-3502", permitRequired: true, permitUrl: "prospertx.gov/building", thirdParty: ["Crossroads Inspections", "Master Code", "Bureau Veritas", "Roadrunner Inspections"] },
  "Richardson": { code: "IPC 2021", population: "121K", region: "North Texas (DFW)", amendments: ["NCTCOG regional amendments apply", "Thermal expansion tank required on all closed water systems", "CSST bonding required per NFPA 54", "Water heater elevation required in garage", "Backflow prevention required on all irrigation connections", "All permits required before work begins"], inspector: "Richardson Building Inspections", phone: "(972) 744-4150", permitRequired: true, permitUrl: "cor.net/permits", thirdParty: ["Crossroads Inspections", "Master Code", "Bureau Veritas", "Roadrunner Inspections"] },
  "Rockwall": { code: "IPC 2021", population: "51K", region: "North Texas (DFW)", amendments: ["Rockwall County seat — smallest county seat in Texas but fast growing", "Verify jurisdiction if working near city limits — ETJ areas may have different rules", "Thermal expansion tank required on all closed water systems", "CSST bonding required per NFPA 54", "Backflow prevention required on all irrigation connections", "Inspections through city portal or by phone"], inspector: "Rockwall Building Inspections", phone: "(972) 771-7700", permitRequired: true, permitUrl: "rockwall.com/buildinginspections", thirdParty: ["Crossroads Inspections", "Master Code", "Bureau Veritas"] },
  "Round Rock": { code: "IPC 2021", population: "133K", region: "Central Texas", amendments: ["Strict one-permit system — all plumbing, electrical, and mechanical must be on the same permit", "All contractors and subcontractors must be registered before permit is issued", "Plumbing cannot commence until permit is obtained and fee paid", "Permit invalid if work not commenced within 6 months of issuance", "Chandler Creek and Vista Oaks MUD areas require same permits as city proper", "Call 512-218-5550 to verify jurisdiction before pulling permit on properties near city limits"], inspector: "Round Rock Building Inspections", phone: "(512) 218-5550", permitRequired: true, permitUrl: "roundrocktexas.gov/building-inspection", thirdParty: ["Fox Energy Specialists", "Burgess Construction Consultants", "Crossroads Inspections", "Bureau Veritas"] },
  "Rowlett": { code: "IPC 2021", population: "66K", region: "North Texas (DFW)", amendments: ["NCTCOG regional amendments apply", "Thermal expansion tank required on all closed water systems", "CSST bonding required per NFPA 54 — inspector will verify", "Water heater elevated 18\" in garage", "Backflow prevention required on all irrigation connections", "All permits required before work begins"], inspector: "Rowlett Building Inspections", phone: "(972) 412-6100", permitRequired: true, permitUrl: "rowlett.com/permits", thirdParty: ["Crossroads Inspections", "Master Code", "Bureau Veritas"] },
  "Sachse": { code: "IPC 2021", population: "30K", region: "North Texas (DFW)", amendments: ["NCTCOG regional amendments apply", "Collin/Dallas county line — verify which county governs your specific address", "Thermal expansion tank required on all closed water systems", "CSST bonding required per NFPA 54", "Backflow prevention required on all irrigation connections", "All permits required before work begins"], inspector: "Sachse Building Inspections", phone: "(972) 495-1212", permitRequired: true, permitUrl: "cityofsachse.com/permits", thirdParty: ["Crossroads Inspections", "Master Code", "Bureau Veritas"] },
  "San Antonio": { code: "IPC 2024", population: "1.4M", region: "South Texas", amendments: ["SAWS approval required before any water service connection", "RPZ backflow required on all commercial irrigation systems", "Gas line pressure test: 10 PSI hold for 15 minutes minimum", "Water heater pan and drain required in all install locations", "Grease trap required on all food service establishments"], inspector: "SA Development Services", phone: "(210) 207-1111", permitRequired: true, permitUrl: "sanantonio.gov/DSD", thirdParty: ["Roadrunner Inspections", "Veritas Inspections", "Bureau Veritas", "ECS Limited"] },
  "Schertz": { code: "IPC 2021", population: "43K", region: "San Antonio Suburb (3 Counties)", amendments: ["Spans Comal, Guadalupe, and Bexar counties — verify which governs your address", "CityView portal for all permits and inspections", "Permits required for plumbing including excavation and trenching of water, sewer, and gas", "Permits required for water heaters and water softener systems", "Permits required for lawn irrigation — including replacement of backflow assemblies, PRVs", "Ordinance 25-S-024: new sign regulations effective June 17, 2025"], inspector: "Schertz Building Inspections", phone: "(210) 619-1750", permitRequired: true, permitUrl: "schertz.com/building", thirdParty: ["Roadrunner Inspections", "Bureau Veritas", "Texas Third Party Inspections LLC", "ECS Limited"], warning: "Schertz spans three counties — Comal, Guadalupe, and Bexar. Always confirm which county governs your specific job address before pulling a permit." },
  "Southlake": { code: "IPC 2021", population: "32K", region: "North Texas (DFW)", amendments: ["IPC 2021 International Building Codes adopted", "Emergency plumbing work allowed without permit — obtain permit at earliest convenience", "FOG (Fats, Oil, Grease) worksheet required for all food service plumbing — must be sealed by plumbing engineer", "Tarrant County Public Health inspects and scores restaurants in Southlake", "CSST bonding required per NFPA 54", "Thermal expansion tank required on all closed water systems"], inspector: "Southlake Building Inspections", phone: "(817) 748-8236", permitRequired: true, permitUrl: "cityofsouthlake.com/permits", thirdParty: ["Crossroads Inspections", "Code Solutions Inc.", "Bureau Veritas", "Master Code"] },
  "Sugar Land": { code: "IPC 2024 ⚠", population: "111K", region: "Greater Houston", amendments: ["⚠ Sugar Land adopted IPC 2024 via Ordinance 2395", "All local amendments in Ordinance 2395 — verify before pulling permit", "New 2024 IPC: showerhead flow limited to 2.0 GPM", "New 2024 IPC: tracer wire required on buried plastic sewer piping", "2023 NEC applies to all electrical work on plumbing-related equipment", "Fort Bend County MUD rules may apply in outer areas — verify jurisdiction"], inspector: "Sugar Land Building Inspections", phone: "(281) 275-2400", permitRequired: true, permitUrl: "sugarlandtx.gov/building", thirdParty: ["Fox Energy Specialists", "Bureau Veritas", "Burgess Construction Consultants", "Roadrunner Inspections"], warning: "Sugar Land is on IPC 2024. Key changes: 2.0 GPM max showerheads, tracer wire on buried plastic sewer. Review IPC 2024 if you've been working under IPC 2021." },
  "Temple": { code: "IPC 2021", population: "82K", region: "Central Texas", amendments: ["Permits required for all plumbing work — no exceptions for minor repairs", "Gas pressure test: 10 PSI minimum hold — inspector notification required", "Thermal expansion tank required on all closed water systems", "Backflow prevention required on all irrigation connections", "Water heater pan and drain required in all interior locations"], inspector: "Temple Building Inspections", phone: "(254) 298-5640", permitRequired: true, permitUrl: "templetx.gov/permits", thirdParty: ["Bureau Veritas", "Texas Third Party Inspections LLC", "Fox Energy Specialists"] },
  "The Colony": { code: "IPC 2024 ⚠", population: "50K", region: "North Texas (DFW)", amendments: ["⚠ The Colony adopted 2024 ICC codes effective July 17, 2025", "All construction documents submitted after July 16, 2025 must reference 2024 codes", "New 2024 IPC: showerhead flow limited to 2.0 GPM", "New 2024 IPC: tracer wire required on buried plastic sewer piping", "Inspections through ETrakIt online portal", "Permits required for roof replacement, siding, and foundation repair (effective Oct 1, 2025)"], inspector: "The Colony Building Inspections", phone: "(972) 625-1106", permitRequired: true, permitUrl: "thecolonytx.gov/building-inspections", thirdParty: ["Crossroads Inspections", "Master Code", "Bureau Veritas"], warning: "The Colony moved to IPC 2024 on July 17, 2025. Also note: permits now required for roof replacement, siding, and foundation repair." },
  "Tyler": { code: "IPC 2021", population: "105K", region: "East Texas", amendments: ["New codes adopted effective January 1, 2024 — verify you have the correct edition", "All building plans must reference code by name and date — permit denied otherwise", "2023 NEC applies to all electrical work associated with plumbing systems", "Permit applications denied if plans do not reference correct code by name and date"], inspector: "Tyler Development Services", phone: "(903) 531-1210", permitRequired: true, permitUrl: "cityoftyler.org/development-services", thirdParty: ["Bureau Veritas", "ECS Limited", "Texas Third Party Inspections LLC"] },
  "Waco": { code: "IPC 2021", population: "139K", region: "Central Texas", amendments: ["Model construction codes enforced with local amendments — verify current amendments", "Gas pressure test: 10 PSI minimum, documented with inspector notification", "Thermal expansion tank required on all closed water systems", "Backflow prevention required on all irrigation and commercial connections", "CSST bonding required per NFPA 54"], inspector: "Waco Inspection Services", phone: "(254) 750-5630", permitRequired: true, permitUrl: "waco-texas.com/inspection-services", thirdParty: ["Bureau Veritas", "Texas Third Party Inspections LLC", "ECS Limited"] },
  "Wichita Falls": { code: "IPC 2021", population: "102K", region: "North Texas", amendments: ["Permits and inspections through MGOconnect online portal", "Plumbing permit application available for download — complete before scheduling", "After-hours, weekend, and emergency inspections available", "All contractors must register and obtain code compliance bond before permit issuance", "Gas pressure test: 10 PSI minimum, witnessed test may be required", "Backflow prevention required on all irrigation systems"], inspector: "Wichita Falls Building Inspections", phone: "(940) 761-7442", permitRequired: true, permitUrl: "wichitafallstx.gov/building-inspections", thirdParty: ["Bureau Veritas", "Texas Third Party Inspections LLC"] },
};

// Remove the null entry
delete JURISDICTIONS["Mansfield_skip"];

const THIRD_PARTY = {
  "Bureau Veritas": { strictAreas: ["Commercial projects: full plan review required before any inspections scheduled", "Documentation heavy — keep all material submittals organized and on site", "Fire protection and plumbing coordination — they inspect systems interaction", "Energy code compliance — will verify plumbing insulation requirements"], tips: ["Largest third-party firm operating in Texas — used on major commercial projects", "Schedule inspections at least 48 hours in advance", "Common fail: missing required plumbing isolation valves on commercial systems", "They operate statewide — same standards apply regardless of city"], builders: ["Commercial & large residential developers statewide"], region: "Statewide Texas" },
  "Burgess Construction Consultants": { strictAreas: ["Quality assurance focused — they verify work quality beyond minimum code", "QAQC documentation — expect detailed reporting on all phases", "Plumbing system performance testing — not just visual inspection", "Energy efficiency verification including hot water system performance"], tips: ["National firm with strong Texas presence — used on larger production communities", "They prioritize quality over speed — build in extra time for their inspections", "Common fail: workmanship issues that meet minimum code but fail QA standards", "Used heavily in master-planned communities across Houston and Austin suburbs"], builders: ["Perry Homes", "Ashton Woods", "Chesmar Homes"], region: "Houston metro, Austin suburbs" },
  "Code Solutions Inc.": { strictAreas: ["Residential plumbing rough-in — they check every item on the IPC checklist", "Water heater installation — elevation, strapping, pan, drain, TPR all verified", "Gas pressure test — require witnessed test with documented results", "Permit documentation must be on site and accessible"], tips: ["North Texas based — operates primarily in Fort Worth and surrounding areas", "Call (817) 379-1129 to schedule", "Common fail: missing or incorrectly sized TPR discharge pipe", "Certified for Fort Worth third-party inspection program"], builders: ["Custom builders and smaller production builders in North Texas"], region: "North Texas, Fort Worth area" },
  "Crossroads Inspections": { strictAreas: ["CSST bonding — they measure distance between every clamp, bring your tape measure", "Water heater strapping — requires double-strap on any unit 40 gal or larger", "Vent termination clearances — will measure to the inch from windows and HVAC intakes", "Pressure test documentation — requires written log with start/end PSI and times"], tips: ["Arrive with written material spec sheets — they will ask for pipe manufacturer info", "Required: photos submitted to their portal before covering any in-slab work", "Common fail: missing dielectric unions on water heater connections", "Call their office by 7AM if you need a same-day inspection slot"], builders: ["DR Horton", "Meritage Homes", "Century Communities"], region: "DFW, Houston, Austin" },
  "ECS Limited": { strictAreas: ["Commercial and mixed-use: MEP systems evaluation for full code compliance", "Domestic water and sanitary sewer systems — quality and efficiency reviewed", "Fire protection and plumbing coordination on commercial projects", "ADA accessibility compliance for plumbing fixture placement"], tips: ["Primarily commercial and institutional projects — less common on residential", "Submit project documentation well in advance of inspection date", "Common fail: plumbing fixture placement violating ADA clearance requirements", "They provide in-depth written reports — review carefully before final walkthrough"], builders: ["Commercial developers, institutional projects"], region: "Statewide Texas (commercial focus)" },
  "Fox Energy Specialists": { strictAreas: ["Unincorporated county areas — they specialize in county/MUD inspections outside city limits", "Foundation plumbing verification — check pipe connections and slope before pour", "Framing/rough-in: plumbing top-out verified alongside electrical and HVAC", "Energy code compliance for plumbing insulation in county jurisdictions"], tips: ["Primary value: they do inspections in unincorporated Texas where no city inspector exists", "ICC Certified Residential Combination Inspectors on staff", "Critical for subdivision work in Harris, Montgomery, Brazoria, and surrounding counties", "Temporary pole inspection included when applicable on new construction"], builders: ["Production builders in unincorporated Harris County and surrounding counties"], region: "Unincorporated Houston metro, Central Texas counties" },
  "L3 Inspections": { strictAreas: ["Residential plumbing and irrigation system inspections", "Pool and spa plumbing — separate inspection from main plumbing system", "Utility and outbuilding plumbing connections", "Sprinkler system backflow verification"], tips: ["Operates in Arlington metro area — licensed and insured", "Offers next-day inspections — good for tight schedules", "100% money-back guarantee", "Common fail: irrigation backflow preventer installation or location"], builders: ["Residential buyers, sellers, and investors in Arlington metro"], region: "Arlington Metro, DFW" },
  "Master Code": { strictAreas: ["Plan review focused — they catch issues before work starts, not after", "Plumbing material compliance — verify all materials are listed and labeled", "CSST bonding documentation — require bond wire size and attachment method", "Cleanout accessibility — must be reachable per code, no exceptions"], tips: ["Based in Arlington — primary coverage in DFW metro", "Submit complete permit applications — incomplete apps cause delays", "Common fail: plans don't match installed work", "Fast turnaround on re-inspections when corrections are straightforward"], builders: ["Various DFW production builders"], region: "DFW Metro" },
  "Roadrunner Inspections": { strictAreas: ["Pressure test duration — they require 4-hour hold minimum, not the standard 1 hour", "Cleanout locations — strict on maximum distance rules, will walk the entire line", "Fixture unit calculations — will request to see your written DFU worksheet", "Horizontal drain slope — they probe with a level on every accessible run"], tips: ["Call ahead the day before — they run tight inspection windows, don't be late", "They prefer all fittings listed on a materials sheet submitted with permit", "Common fail: improper slope on long horizontal drain runs in slab", "They photograph every inspection — keep your work clean and labeled"], builders: ["Lennar", "Taylor Morrison", "Pulte Homes"], region: "Houston, San Antonio, DFW" },
  "Texas Third Party Inspections LLC": { strictAreas: ["Residential new construction phase inspections — foundation through final", "Plumbing rough-in at foundation: pipe connections and slope verified before pour", "Top-out inspection: all venting, fixture rough-ins, and pressure test", "Final inspection: all fixtures installed, no open connections, permits in order"], tips: ["Smaller firm — often more accessible and responsive than national companies", "Good for smaller builders who need flexible scheduling", "Common fail: foundation plumbing slope insufficient before slab pour", "Statewide coverage across Texas"], builders: ["Smaller custom and semi-custom builders across Texas"], region: "Statewide Texas" },
  "Veritas Inspections": { strictAreas: ["Gas documentation — requires manufacturer spec sheets physically on site", "Water service depth — they probe with a rod for minimum 12\" cover", "Shower pan liner — flood test required for full 24 hours before sign-off", "TPR valve discharge — checks material, size, length, and termination point"], tips: ["Most thorough of the major third-party firms operating in Texas", "Submit digital as-builts 48 hours before they arrive on commercial jobs", "Common fail: TPR discharge pipe wrong material or terminates too high", "They will re-inspect failed items at no charge if corrected within 48 hours"], builders: ["Toll Brothers", "Highland Homes", "David Weekley"], region: "Austin, DFW, San Antonio, Houston" },
};

const CODES = [
  { id: 1, category: "Venting", title: "Minimum vent pipe diameter", code: "IPC 903.1", plain: "No vent pipe shall be less than 1¼ inches in diameter. Individual vents for sinks and lavatories may use 1¼\" but main stacks require a minimum of 3\". Vent pipe must be the same diameter as the drain it serves or not less than 1¼\".", tags: ["vent", "pipe size", "diameter", "stack"] },
  { id: 2, category: "Water Heaters", title: "Thermal expansion tank", code: "IPC 607.3", plain: "A thermal expansion tank is required whenever a backflow preventer, check valve, or pressure reducing valve creates a closed system on the cold water supply to the water heater. Size the tank to the water heater capacity.", tags: ["water heater", "expansion tank", "closed system"] },
  { id: 3, category: "Drainage", title: "Horizontal drain slope", code: "IPC 704.1", plain: "Horizontal drainage pipes must slope uniformly not less than ¼ inch per foot toward the point of disposal for pipes 2½\" or smaller. Pipes 3\" and larger may slope at ⅛\" per foot minimum. No horizontal drain shall be installed level.", tags: ["drain", "slope", "horizontal", "grade"] },
  { id: 4, category: "Water Supply", title: "Pressure reducing valve", code: "IPC 604.8", plain: "Where the water pressure supplied exceeds 80 PSI, a pressure reducing valve is required on the building water service. Set the PRV to deliver between 60–80 PSI downstream. PRV must be accessible for service.", tags: ["pressure", "PRV", "water supply", "80 PSI"] },
  { id: 5, category: "Gas", title: "CSST bonding requirement", code: "NFPA 54 7.13", plain: "Corrugated Stainless Steel Tubing (CSST) must be electrically bonded to the building's grounding electrode system. Many Texas cities require a bonding clamp every 6 feet along the run. Always check local amendments — this varies by city.", tags: ["CSST", "gas", "bonding", "grounding"] },
  { id: 6, category: "Backflow", title: "Irrigation backflow prevention", code: "IPC 608.16.5", plain: "All lawn irrigation systems connected to a potable water supply must have a backflow preventer. A pressure vacuum breaker (PVB) is the minimum for residential. A reduced pressure zone (RPZ) assembly is required where chemicals or fertilizers are injected.", tags: ["backflow", "irrigation", "PVB", "RPZ"] },
  { id: 7, category: "Fixtures", title: "Shower pressure balance valves", code: "IPC 412.3", plain: "All shower and tub/shower combination controls must be pressure-balancing or thermostatic mixing valves. Maximum delivered water temperature is 120°F. Required in all new construction and replacements.", tags: ["shower", "valve", "scald", "pressure balance"] },
  { id: 8, category: "Drainage", title: "Cleanout spacing and access", code: "IPC 708.1", plain: "Cleanouts are required at each change of direction greater than 45° in horizontal drainage lines, and at maximum 100-foot intervals. Cleanouts must be accessible and installed in the direction of flow for rodding.", tags: ["cleanout", "access", "drain", "100 feet"] },
  { id: 9, category: "Water Heaters", title: "Water heater TPR valve", code: "IPC 504.6", plain: "Every water heater must have a temperature and pressure relief (TPR) valve installed. The discharge pipe must be the same size as the valve outlet, run full length to within 6\" of the floor or to a drain, and terminate in a visible location.", tags: ["TPR", "water heater", "relief valve", "safety"] },
  { id: 10, category: "Gas", title: "Gas pressure test requirements", code: "IFGC 406.4", plain: "Gas piping systems must be tested with air, nitrogen, or CO2 at a minimum of 10 PSI for a minimum of 15 minutes. Many Texas cities require 30 minutes. Never test with gas. Document start and end pressures. Inspector may require witnessed test.", tags: ["gas", "pressure test", "10 PSI", "leak test"] },
  { id: 11, category: "Water Supply", title: "Water service pipe materials", code: "IPC 605.3", plain: "Water service pipe from the meter to the building must be approved materials: Type K or L copper, HDPE, or PVC (AWWA C900). Many Texas cities restrict to copper within a set distance of the meter. Always verify local amendments.", tags: ["water service", "pipe material", "copper", "HDPE"] },
  { id: 12, category: "Venting", title: "Wet venting requirements", code: "IPC 908.1", plain: "A wet vent may serve as both a drain and a vent for fixtures on the same floor. The wet vent must be one pipe size larger than required for the drain alone. Wet venting is limited to bathroom groups only — cannot wet vent kitchen sinks.", tags: ["wet vent", "vent", "bathroom group", "drain"] },
  { id: 13, category: "Drainage", title: "Fixture unit values (DFU)", code: "IPC Table 709.1", plain: "Each fixture is assigned a Drainage Fixture Unit (DFU) value: Toilet = 4, Shower = 2, Lavatory = 1, Kitchen sink = 2, Clothes washer = 3, Floor drain = 2. Sum all DFU values to size the building drain and sewer.", tags: ["DFU", "fixture units", "drain sizing"] },
  { id: 14, category: "Backflow", title: "Hose bibb vacuum breaker", code: "IPC 608.15.4.1", plain: "All outdoor hose connection sillcocks must have an integral or field-installed vacuum breaker. This prevents contaminated water from being siphoned back into the potable supply when a hose is submerged. Non-removable type required.", tags: ["hose bibb", "vacuum breaker", "sillcock", "backflow"] },
  { id: 15, category: "Water Heaters", title: "Water heater seismic strapping", code: "IPC 507.2", plain: "Water heaters must be strapped or braced in designated seismic zones. In Texas, many city jurisdictions and third-party inspectors require strapping in garages even outside the strict code mandate.", tags: ["water heater", "strapping", "seismic", "garage"] },
  { id: 16, category: "Water Supply", title: "Showerhead flow rate — IPC 2024", code: "IPC 2024 408.2", plain: "The 2024 IPC limits showerhead flow to a maximum of 2.0 GPM. Applies in cities on IPC 2024: Plano (Aug 2025), The Colony (Jul 2025), Flower Mound (Oct 2025), Frisco (Mar 2026), McAllen (Jan 2026), Killeen, Sugar Land, San Antonio. Verify your city before selecting fixtures.", tags: ["showerhead", "flow rate", "GPM", "IPC 2024", "water conservation"] },
  { id: 17, category: "Drainage", title: "Tracer wire — buried plastic pipe (IPC 2024)", code: "IPC 2024 305.6", plain: "The 2024 IPC requires tracer wire on all buried plastic sewer piping. Wire must be continuous and accessible at each end. Applies in cities on IPC 2024. Not required under IPC 2021.", tags: ["tracer wire", "buried pipe", "sewer", "IPC 2024"] },
];

const Icon = ({ name, size = 20, color = "currentColor" }) => {
  const icons = {
    home: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>,
    book: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"/></svg>,
    map: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="10" r="3"/><path d="M12 21.7C17.3 17 20 13 20 10a8 8 0 1 0-16 0c0 3 2.7 6.9 8 11.7z"/></svg>,
    user: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>,
    search: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>,
    mic: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 1a3 3 0 0 0-3 3v8a3 3 0 0 0 6 0V4a3 3 0 0 0-3-3z"/><path d="M19 10v2a7 7 0 0 1-14 0v-2"/><line x1="12" y1="19" x2="12" y2="23"/><line x1="8" y1="23" x2="16" y2="23"/></svg>,
    chevron: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="9 18 15 12 9 6"/></svg>,
    back: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="15 18 9 12 15 6"/></svg>,
    bookmark: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/></svg>,
    x: <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2.5" strokeLinecap="round"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>,
  };
  return icons[name] || null;
};

export default function App() {
  const [screen, setScreen] = useState("home");
  const [selectedJurisdiction, setSelectedJurisdiction] = useState(null);
  const [selectedThirdParty, setSelectedThirdParty] = useState(null);
  const [searchQuery, setSearchQuery] = useState("");
  const [jSearchQuery, setJSearchQuery] = useState("");
  const [selectedCategory, setSelectedCategory] = useState("All");
  const [selectedCode, setSelectedCode] = useState(null);
  const [bookmarks, setBookmarks] = useState([1, 5]);
  const [isListening, setIsListening] = useState(false);
  const [voiceStatus, setVoiceStatus] = useState("");
  const recognitionRef = useRef(null);

  const startVoice = () => {
    const SR = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (!SR) { setVoiceStatus("Voice not supported on this browser"); setTimeout(() => setVoiceStatus(""), 3000); return; }
    if (recognitionRef.current) recognitionRef.current.stop();
    const r = new SR();
    recognitionRef.current = r;
    r.continuous = false; r.interimResults = false; r.lang = "en-US";
    r.onstart = () => { setIsListening(true); setVoiceStatus("Listening..."); };
    r.onresult = (e) => {
      const t = e.results[0][0].transcript.toLowerCase().trim();
      setVoiceStatus(`Heard: "${t}"`); setIsListening(false);
      const cityNames = Object.keys(JURISDICTIONS).map(c => c.toLowerCase());
      const matchCity = cityNames.find(c => t.includes(c));
      if (matchCity) {
        const city = Object.keys(JURISDICTIONS).find(c => c.toLowerCase() === matchCity);
        setScreen("jurisdiction"); setSelectedJurisdiction(city);
      } else if (t.includes("city") || t.includes("jurisdiction") || t.includes("permit")) {
        setScreen("jurisdiction"); setJSearchQuery(t.replace(/city|jurisdiction|search|find|show me|what about|permits? for/gi, "").trim()); setSelectedJurisdiction(null);
      } else if (t.includes("inspector") || t.includes("inspection") || t.includes("crossroads") || t.includes("veritas") || t.includes("roadrunner") || t.includes("bureau")) {
        setScreen("inspectors"); setSelectedThirdParty(null);
      } else {
        setScreen("codes"); setSearchQuery(t); setSelectedCode(null);
      }
      setTimeout(() => setVoiceStatus(""), 3000);
    };
    r.onerror = (e) => { setIsListening(false); setVoiceStatus(e.error === "not-allowed" ? "Mic permission denied" : "Could not hear — try again"); setTimeout(() => setVoiceStatus(""), 3000); };
    r.onend = () => setIsListening(false);
    r.start();
  };
  const stopVoice = () => { if (recognitionRef.current) recognitionRef.current.stop(); setIsListening(false); setVoiceStatus(""); };

  const categories = ["All", ...new Set(CODES.map(c => c.category))];
  const filteredCodes = CODES.filter(c => { const q = searchQuery.toLowerCase(); const matchCat = selectedCategory === "All" || c.category === selectedCategory; return matchCat && (!q || c.title.toLowerCase().includes(q) || c.tags.some(t => t.toLowerCase().includes(q)) || c.code.toLowerCase().includes(q) || c.plain.toLowerCase().includes(q)); });
  const sortedJ = Object.entries(JURISDICTIONS).filter(([,v]) => v).sort(([a], [b]) => a.localeCompare(b));
  const filteredJ = sortedJ.filter(([city]) => !jSearchQuery || city.toLowerCase().includes(jSearchQuery.toLowerCase()));
  const toggleBookmark = (id) => setBookmarks(prev => prev.includes(id) ? prev.filter(b => b !== id) : [...prev, id]);
  const goBack = () => { if (selectedCode) { setSelectedCode(null); return; } if (selectedJurisdiction) { setSelectedJurisdiction(null); return; } if (selectedThirdParty) { setSelectedThirdParty(null); return; } };
  const showBack = selectedCode || selectedJurisdiction || selectedThirdParty;
  const navTo = (s) => { setScreen(s); setSelectedCode(null); setSelectedJurisdiction(null); setSelectedThirdParty(null); setSearchQuery(""); setJSearchQuery(""); setSelectedCategory("All"); };
  const catColors = { "Venting": "#4a9a8a", "Water Heaters": "#c87a20", "Drainage": "#5a7aaa", "Water Supply": "#2a8a6a", "Gas": "#c85a30", "Backflow": "#8a5aaa", "Fixtures": "#8a8a30" };
  const cityCount = sortedJ.length;

  return (
    <div style={{ fontFamily: "'Georgia',serif", background: "#111518", minHeight: "100vh", maxWidth: 430, margin: "0 auto", display: "flex", flexDirection: "column" }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@400;600;700&family=Lora:ital,wght@0,400;0,600;1,400&display=swap');
        *{box-sizing:border-box;margin:0;padding:0;-webkit-tap-highlight-color:transparent}
        body{background:#111518}
        ::-webkit-scrollbar{display:none}
        .p{transition:opacity .15s,transform .15s;cursor:pointer;-webkit-user-select:none;user-select:none}
        .p:active{opacity:.7;transform:scale(.98)}
        .cc{background:#1a1f24;border:1px solid #2a3038;border-radius:12px;padding:16px;margin-bottom:10px}
        .jc{background:#1a1f24;border:1px solid #2a3038;border-radius:12px;padding:16px;margin-bottom:10px;display:flex;align-items:center;gap:12px}
        .jc:active{background:#1f252c}
        .pill{display:inline-flex;align-items:center;background:rgba(255,255,255,.06);border-radius:20px;padding:3px 10px;font-size:11px;font-family:'Barlow Condensed',sans-serif;letter-spacing:.05em;font-weight:600}
        .sw{position:relative;margin-bottom:14px}
        .si{width:100%;background:#1a1f24;border:1px solid #2a3038;border-radius:10px;padding:12px 48px 12px 42px;color:#e0e8f0;font-family:'Lora',serif;font-size:15px;outline:none;transition:border-color .2s}
        .si:focus{border-color:#3a8a9a}
        .si::placeholder{color:#3a4a5a}
        .sic{position:absolute;left:13px;top:50%;transform:translateY(-50%);pointer-events:none;color:#4a5a6a}
        .mb{position:absolute;right:10px;top:50%;transform:translateY(-50%);background:none;border:none;cursor:pointer;padding:6px;border-radius:50%;display:flex;align-items:center;justify-content:center}
        .mb.on{animation:pulse 1s infinite}
        @keyframes pulse{0%,100%{opacity:1}50%{opacity:.4}}
        .cs{display:flex;gap:8px;overflow-x:auto;padding-bottom:2px;margin-bottom:16px}
        .cb{flex-shrink:0;background:#1a1f24;border:1px solid #2a3038;border-radius:20px;padding:6px 14px;color:#6a8a9a;font-family:'Barlow Condensed',sans-serif;font-size:13px;font-weight:600;letter-spacing:.05em;cursor:pointer;transition:all .15s;white-space:nowrap}
        .cb.active{background:#1a3a4a;border-color:#3a8a9a;color:#7acae0}
        .sl{font-family:'Barlow Condensed',sans-serif;font-size:11px;letter-spacing:.15em;font-weight:700;color:#3a5a6a;text-transform:uppercase;margin-bottom:10px}
        .ar{display:flex;gap:10px;padding:12px 0;border-bottom:1px solid #1e2428;align-items:flex-start}
        .ar:last-child{border-bottom:none}
        .dot{width:6px;height:6px;border-radius:50%;background:#3a8a9a;margin-top:7px;flex-shrink:0}
        .wd{background:#c87a20}.rd{background:#c85a40}
        .nb{position:fixed;bottom:0;left:50%;transform:translateX(-50%);width:100%;max-width:430px;background:#151a1f;border-top:1px solid #1e2428;display:flex;padding:8px 0 20px;z-index:100}
        .ni{flex:1;display:flex;flex-direction:column;align-items:center;gap:4px;padding:6px 0;cursor:pointer}
        .ni:active{opacity:.6}
        .nl{font-family:'Barlow Condensed',sans-serif;font-size:10px;letter-spacing:.08em;font-weight:600}
        .hdr{position:sticky;top:0;background:#111518;border-bottom:1px solid #1e2428;z-index:50;padding:0 16px;display:flex;align-items:center;height:56px;gap:12px}
        .cnt{flex:1;overflow-y:auto;padding:16px 16px 90px}
        .hb{background:#1a1f24;border:1px solid #2a3038;border-radius:14px;padding:18px 16px;display:flex;align-items:center;gap:14px;margin-bottom:10px;cursor:pointer}
        .hb:active{background:#1f252c}
        .ib{background:#1a1f24;border:1px solid #2a3038;border-radius:12px;padding:16px;margin-bottom:12px}
        .wb{background:#1a1a0f;border:1px solid #4a4a1a;border-radius:10px;padding:12px 14px;margin-bottom:16px}
        .tc{background:#1a2a1a;border:1px solid #2a4a2a;border-radius:8px;padding:8px 12px;display:inline-flex;align-items:center;gap:6px;margin:4px;cursor:pointer}
        .tc:active{opacity:.7}
        .vb{background:#1a2a3a;border-bottom:1px solid #2a4a6a;padding:8px 16px;display:flex;align-items:center;gap:10px}
        .vbig{width:100%;background:linear-gradient(135deg,#1a3a4a,#0f2030);border:1px solid #3a8a9a;border-radius:14px;padding:18px;display:flex;align-items:center;gap:12px;cursor:pointer;margin-bottom:16px}
        .vbig.on{border-color:#c85a30;background:linear-gradient(135deg,#2a1a0f,#1a0f08)}
        .vbig:active{opacity:.8;transform:scale(.98)}
      `}</style>

      <div className="hdr">
        {showBack ? (
          <div className="p" onClick={goBack} style={{ color: "#7acae0", display: "flex", alignItems: "center", gap: 4 }}>
            <Icon name="back" size={22} color="#7acae0" />
            <span style={{ fontFamily: "'Barlow Condensed',sans-serif", fontSize: 14, fontWeight: 600, letterSpacing: ".05em" }}>BACK</span>
          </div>
        ) : (
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <div style={{ width: 30, height: 30, background: "linear-gradient(135deg,#2a6a8a,#1a4a6a)", borderRadius: 8, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 15 }}>🔧</div>
            <div>
              <div style={{ fontFamily: "'Barlow Condensed',sans-serif", fontWeight: 700, fontSize: 20, letterSpacing: ".1em", color: "#e0e8f0", lineHeight: 1 }}>CODEX TX</div>
              <div style={{ fontFamily: "'Barlow Condensed',sans-serif", fontSize: 9, color: "#3a5a6a", letterSpacing: ".15em" }}>TEXAS PLUMBING CODE</div>
            </div>
          </div>
        )}
        <div style={{ marginLeft: "auto", display: "flex", alignItems: "center", gap: 8 }}>
          <button onClick={isListening ? stopVoice : startVoice} style={{ background: isListening ? "rgba(200,90,48,.2)" : "rgba(58,138,154,.15)", border: `1px solid ${isListening ? "#c85a30" : "#3a8a9a"}`, borderRadius: 8, padding: "6px 10px", display: "flex", alignItems: "center", gap: 5, cursor: "pointer" }}>
            <Icon name="mic" size={15} color={isListening ? "#c85a30" : "#7acae0"} />
            <span style={{ fontFamily: "'Barlow Condensed',sans-serif", fontSize: 11, color: isListening ? "#c85a30" : "#7acae0", fontWeight: 700, letterSpacing: ".06em" }}>{isListening ? "STOP" : "VOICE"}</span>
          </button>
          <span style={{ background: "#1a3a2a", border: "1px solid #2a6a3a", borderRadius: 6, padding: "3px 8px", fontFamily: "'Barlow Condensed',sans-serif", fontSize: 11, color: "#4a9a6a", letterSpacing: ".08em", fontWeight: 700 }}>TEXAS</span>
        </div>
      </div>

      {voiceStatus && <div className="vb"><Icon name="mic" size={14} color={isListening ? "#c85a30" : "#7acae0"} /><span style={{ fontFamily: "'Lora',serif", fontStyle: "italic", fontSize: 13, color: isListening ? "#c87a60" : "#7acae0", flex: 1 }}>{voiceStatus}</span></div>}

      <div className="cnt">
        {screen === "home" && (
          <div>
            <div style={{ marginBottom: 20 }}>
              <div style={{ fontFamily: "'Barlow Condensed',sans-serif", fontWeight: 700, fontSize: 34, letterSpacing: ".04em", color: "#e0e8f0", lineHeight: 1.1, marginBottom: 6 }}>The code book<br /><span style={{ color: "#3a8a9a" }}>in your pocket.</span></div>
              <div style={{ fontFamily: "'Lora',serif", fontStyle: "italic", fontSize: 14, color: "#4a6a7a", lineHeight: 1.6 }}>{cityCount} Texas cities · {Object.keys(THIRD_PARTY).length} inspector profiles · {CODES.length} codes</div>
            </div>
            <button className={`vbig ${isListening ? "on" : ""}`} onClick={isListening ? stopVoice : startVoice}>
              <Icon name="mic" size={26} color={isListening ? "#c85a30" : "#7acae0"} />
              <div style={{ textAlign: "left" }}>
                <div style={{ fontFamily: "'Barlow Condensed',sans-serif", fontWeight: 700, fontSize: 17, letterSpacing: ".06em", color: isListening ? "#c87a60" : "#c0d8e8" }}>{isListening ? "LISTENING... TAP TO STOP" : "TAP TO SEARCH BY VOICE"}</div>
                <div style={{ fontFamily: "'Lora',serif", fontSize: 12, color: "#3a5a6a", marginTop: 2 }}>{isListening ? "Say a city name, code topic, or inspector" : "Hands dirty? Just say what you need"}</div>
              </div>
            </button>
            <div style={{ marginBottom: 20 }}>
              <div className="sl">Quick Access</div>
              {[{ s: "codes", icon: "book", bg: "#1a3a4a", ic: "#7acae0", t: "CODE REFERENCE", sub: "Search Texas IPC & UPC in plain English" }, { s: "jurisdiction", icon: "map", bg: "#1a3a2a", ic: "#4a9a6a", t: "JURISDICTION LOOKUP", sub: `${cityCount} cities — amendments & contacts` }, { s: "inspectors", icon: "user", bg: "#2a2a1a", ic: "#c8a030", t: "INSPECTOR PROFILES", sub: "What third-party inspectors look for" }].map(item => (
                <div key={item.s} className="hb p" onClick={() => navTo(item.s)}>
                  <div style={{ width: 42, height: 42, background: item.bg, borderRadius: 10, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}><Icon name={item.icon} size={20} color={item.ic} /></div>
                  <div><div style={{ fontFamily: "'Barlow Condensed',sans-serif", fontWeight: 700, fontSize: 17, letterSpacing: ".05em", color: "#e0e8f0", marginBottom: 2 }}>{item.t}</div><div style={{ fontFamily: "'Lora',serif", fontSize: 12, color: "#4a6a7a" }}>{item.sub}</div></div>
                  <div style={{ marginLeft: "auto", color: "#3a5a6a" }}><Icon name="chevron" size={18} /></div>
                </div>
              ))}
            </div>
            {bookmarks.length > 0 && <div><div className="sl">Saved Codes</div>{CODES.filter(c => bookmarks.includes(c.id)).map(c => <div key={c.id} className="cc p" onClick={() => { setScreen("codes"); setSelectedCode(c); }}><div style={{ display: "flex", justifyContent: "space-between" }}><div style={{ fontFamily: "'Barlow Condensed',sans-serif", fontWeight: 600, fontSize: 15, color: "#c0d8e8", flex: 1, paddingRight: 8 }}>{c.title}</div><span className="pill" style={{ color: catColors[c.category] || "#7a9aaa" }}>{c.code}</span></div></div>)}</div>}
          </div>
        )}

        {screen === "codes" && !selectedCode && (
          <div>
            <div className="sw"><div className="sic"><Icon name="search" size={16} /></div><input className="si" placeholder="Search codes, topics, keywords..." value={searchQuery} onChange={e => setSearchQuery(e.target.value)} /><button className={`mb ${isListening ? "on" : ""}`} onClick={isListening ? stopVoice : startVoice}><Icon name="mic" size={16} color={isListening ? "#c85a30" : "#3a8a9a"} /></button></div>
            <div className="cs">{categories.map(c => <button key={c} className={`cb ${selectedCategory === c ? "active" : ""}`} onClick={() => setSelectedCategory(c)}>{c}</button>)}</div>
            <div style={{ fontFamily: "'Lora',serif", fontSize: 12, color: "#3a5a6a", marginBottom: 12 }}>{filteredCodes.length} code{filteredCodes.length !== 1 ? "s" : ""} {searchQuery ? "matching" : "available"}</div>
            {filteredCodes.map(code => <div key={code.id} className="cc p" onClick={() => setSelectedCode(code)}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 6 }}><div style={{ fontFamily: "'Barlow Condensed',sans-serif", fontWeight: 600, fontSize: 16, color: "#c0d8e8", flex: 1, paddingRight: 8 }}>{code.title}</div><span className="pill" style={{ color: catColors[code.category] || "#7a9aaa", flexShrink: 0 }}>{code.code}</span></div><div style={{ fontFamily: "'Lora',serif", fontSize: 13, color: "#4a6a7a", lineHeight: 1.5, marginBottom: 10 }}>{code.plain.substring(0, 85)}…</div><div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>{code.tags.slice(0, 3).map(t => <span key={t} className="pill" style={{ color: "#4a6a7a", fontSize: 10 }}>{t}</span>)}</div></div>)}
          </div>
        )}

        {screen === "codes" && selectedCode && (
          <div>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}><span className="pill" style={{ color: catColors[selectedCode.category] || "#7a9aaa", fontSize: 12 }}>{selectedCode.category}</span><div className="p" style={{ padding: 8 }} onClick={() => toggleBookmark(selectedCode.id)}><Icon name="bookmark" size={22} color={bookmarks.includes(selectedCode.id) ? "#7acae0" : "#3a5a6a"} /></div></div>
            <div style={{ fontFamily: "'Barlow Condensed',sans-serif", fontWeight: 700, fontSize: 26, letterSpacing: ".04em", color: "#e0e8f0", lineHeight: 1.15, marginBottom: 6 }}>{selectedCode.title.toUpperCase()}</div>
            <div style={{ fontFamily: "'Barlow Condensed',sans-serif", fontSize: 13, color: "#3a8a9a", letterSpacing: ".1em", marginBottom: 20 }}>{selectedCode.code}</div>
            <div className="sl">Plain English</div>
            <div className="ib"><p style={{ fontFamily: "'Lora',serif", fontSize: 15, lineHeight: 1.75, color: "#c0d0d8" }}>{selectedCode.plain}</p></div>
            <div className="sl" style={{ marginTop: 16 }}>Tags</div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>{selectedCode.tags.map(t => <span key={t} className="pill" style={{ color: "#4a7a8a", fontSize: 12, padding: "5px 12px" }}>{t}</span>)}</div>
            <div style={{ marginTop: 20, padding: "12px 14px", background: "#1a2a1a", border: "1px solid #2a4a2a", borderRadius: 10 }}><div style={{ fontFamily: "'Barlow Condensed',sans-serif", fontSize: 11, letterSpacing: ".1em", color: "#3a7a3a", marginBottom: 4 }}>⚠ ALWAYS VERIFY</div><div style={{ fontFamily: "'Lora',serif", fontSize: 12, color: "#4a6a4a", lineHeight: 1.5 }}>Local amendments may override this code. Check your jurisdiction before pulling a permit.</div></div>
          </div>
        )}

        {screen === "jurisdiction" && !selectedJurisdiction && (
          <div>
            <div className="sw"><div className="sic"><Icon name="search" size={16} /></div><input className="si" placeholder="Search cities or use voice..." value={jSearchQuery} onChange={e => setJSearchQuery(e.target.value)} /><button className={`mb ${isListening ? "on" : ""}`} onClick={isListening ? stopVoice : startVoice}><Icon name="mic" size={16} color={isListening ? "#c85a30" : "#3a8a9a"} /></button></div>
            <div style={{ fontFamily: "'Lora',serif", fontSize: 12, color: "#3a5a6a", marginBottom: 14 }}>{filteredJ.length} Texas jurisdictions — A to Z</div>
            {filteredJ.map(([city, data]) => <div key={city} className="jc p" onClick={() => setSelectedJurisdiction(city)}><div style={{ width: 38, height: 38, background: data.code.includes("UPC") ? "#2a1a1a" : "#1a3a2a", borderRadius: 9, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}><Icon name="map" size={18} color={data.code.includes("UPC") ? "#c87a50" : "#4a9a6a"} /></div><div style={{ flex: 1 }}><div style={{ fontFamily: "'Barlow Condensed',sans-serif", fontWeight: 700, fontSize: 17, color: "#e0e8f0", marginBottom: 2 }}>{city}</div><div style={{ fontFamily: "'Lora',serif", fontSize: 12, color: "#4a6a7a" }}>{data.amendments.length} amendments · {data.code} · {data.region}</div></div><Icon name="chevron" size={16} color="#3a5a6a" /></div>)}
          </div>
        )}

        {screen === "jurisdiction" && selectedJurisdiction && (() => {
          const j = JURISDICTIONS[selectedJurisdiction];
          return (
            <div>
              <div style={{ marginBottom: 12 }}><div style={{ fontFamily: "'Barlow Condensed',sans-serif", fontWeight: 700, fontSize: 32, letterSpacing: ".06em", color: "#e0e8f0", lineHeight: 1 }}>{selectedJurisdiction.toUpperCase()}</div><div style={{ fontFamily: "'Lora',serif", fontSize: 13, color: "#4a6a7a", marginTop: 4 }}>{j.region} · Pop. {j.population}</div></div>
              <div style={{ display: "flex", gap: 8, marginBottom: 16, flexWrap: "wrap" }}><span className="pill" style={{ color: j.code.includes("UPC") ? "#c87a50" : "#4a9a6a", background: j.code.includes("UPC") ? "#2a1a1a" : "#1a3a2a", padding: "5px 12px" }}>{j.code}</span>{j.permitRequired && <span className="pill" style={{ color: "#c8a030", background: "#2a2a1a", padding: "5px 12px" }}>PERMIT REQUIRED</span>}</div>
              {j.warning && <div className="wb"><div style={{ fontFamily: "'Barlow Condensed',sans-serif", fontSize: 11, letterSpacing: ".1em", color: "#8a8a20", marginBottom: 4 }}>⚠ IMPORTANT NOTE</div><div style={{ fontFamily: "'Lora',serif", fontSize: 13, color: "#c8c870", lineHeight: 1.5 }}>{j.warning}</div></div>}
              <div className="sl">Local Amendments</div>
              <div className="ib" style={{ marginBottom: 16 }}>{j.amendments.map((a, i) => <div key={i} className="ar"><div className="dot" /><div style={{ fontFamily: "'Lora',serif", fontSize: 14, color: "#b0c8d8", lineHeight: 1.6 }}>{a}</div></div>)}</div>
              {j.thirdParty && j.thirdParty.length > 0 && <><div className="sl">Third-Party Inspectors Active Here</div><div style={{ display: "flex", flexWrap: "wrap", marginBottom: 16 }}>{j.thirdParty.map(tp => <div key={tp} className="tc p" onClick={() => { setSelectedThirdParty(tp); setScreen("inspectors"); }}><span style={{ fontFamily: "'Barlow Condensed',sans-serif", fontSize: 13, color: "#4a9a6a", fontWeight: 600 }}>{tp}</span><Icon name="chevron" size={12} color="#2a6a2a" /></div>)}</div></>}
              <div className="sl">Inspection Office</div>
              <div className="ib"><div style={{ fontFamily: "'Barlow Condensed',sans-serif", fontWeight: 600, fontSize: 16, color: "#e0e8f0", marginBottom: 8 }}>{j.inspector}</div><div style={{ fontFamily: "'Lora',serif", fontSize: 14, color: "#c0d8c8" }}>📞 {j.phone}</div>{j.permitUrl && <div style={{ marginTop: 8, fontFamily: "'Lora',serif", fontSize: 12, color: "#3a5a6a" }}>🌐 {j.permitUrl}</div>}</div>
            </div>
          );
        })()}

        {screen === "inspectors" && !selectedThirdParty && (
          <div>
            <div style={{ fontFamily: "'Lora',serif", fontStyle: "italic", fontSize: 14, color: "#4a6a7a", lineHeight: 1.6, marginBottom: 20 }}>Builder jobs often use third-party inspectors with requirements beyond city code. Know what they look for before you show up.</div>
            <div className="sl">{Object.keys(THIRD_PARTY).length} Inspector Profiles</div>
            {Object.entries(THIRD_PARTY).sort(([a], [b]) => a.localeCompare(b)).map(([name, data]) => <div key={name} className="jc p" onClick={() => setSelectedThirdParty(name)}><div style={{ width: 38, height: 38, background: "#2a2a1a", borderRadius: 9, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}><Icon name="user" size={18} color="#c8a030" /></div><div style={{ flex: 1 }}><div style={{ fontFamily: "'Barlow Condensed',sans-serif", fontWeight: 700, fontSize: 16, color: "#e0e8f0", marginBottom: 2 }}>{name}</div><div style={{ fontFamily: "'Lora',serif", fontSize: 12, color: "#4a6a7a" }}>{data.strictAreas.length} strict areas · {data.region}</div></div><Icon name="chevron" size={16} color="#3a5a6a" /></div>)}
          </div>
        )}

        {screen === "inspectors" && selectedThirdParty && (() => {
          const ins = THIRD_PARTY[selectedThirdParty];
          return (
            <div>
              <div style={{ marginBottom: 20 }}><div style={{ fontFamily: "'Barlow Condensed',sans-serif", fontWeight: 700, fontSize: 28, letterSpacing: ".05em", color: "#e0e8f0", lineHeight: 1.1 }}>{selectedThirdParty.toUpperCase()}</div><div style={{ fontFamily: "'Lora',serif", fontSize: 13, color: "#4a6a7a", marginTop: 4 }}>{ins.region}</div><div style={{ marginTop: 8, display: "flex", flexWrap: "wrap", gap: 6 }}>{ins.builders.map(b => <span key={b} className="pill" style={{ color: "#c8a030", background: "#2a2a1a", padding: "4px 10px", fontSize: 11 }}>{b}</span>)}</div></div>
              <div className="sl" style={{ color: "#8a4a3a" }}>Strict On These Areas</div>
              <div className="ib" style={{ marginBottom: 16, borderColor: "#3a2020" }}>{ins.strictAreas.map((a, i) => <div key={i} className="ar"><div className="dot rd" /><div style={{ fontFamily: "'Lora',serif", fontSize: 14, color: "#d0a8a0", lineHeight: 1.6 }}>{a}</div></div>)}</div>
              <div className="sl" style={{ color: "#7a6a20" }}>Field Tips</div>
              <div className="ib" style={{ borderColor: "#3a2a10" }}>{ins.tips.map((t, i) => <div key={i} className="ar"><div className="dot wd" /><div style={{ fontFamily: "'Lora',serif", fontSize: 14, color: "#d0c080", lineHeight: 1.6 }}>{t}</div></div>)}</div>
            </div>
          );
        })()}
      </div>

      <div className="nb">
        {[{ id: "home", label: "HOME", icon: "home", color: "#7acae0" }, { id: "codes", label: "CODES", icon: "book", color: "#7acae0" }, { id: "jurisdiction", label: "CITIES", icon: "map", color: "#4a9a6a" }, { id: "inspectors", label: "INSPECTORS", icon: "user", color: "#c8a030" }].map(item => {
          const active = screen === item.id;
          return <div key={item.id} className="ni" onClick={() => navTo(item.id)}><Icon name={item.icon} size={22} color={active ? item.color : "#3a4a5a"} /><span className="nl" style={{ color: active ? item.color : "#3a4a5a" }}>{item.label}</span></div>;
        })}
      </div>
    </div>
  );
}
